# Generated by Django 4.2.7 on 2023-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=255)),
                ('desc_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inflected_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflected_form', models.CharField(max_length=255)),
                ('link_text', models.CharField(max_length=255)),
            ],
        ),
    ]
